--코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY') AS "YEAR",
        TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS "MONTH",
        GENDER AS "GENDER", 
        COUNT(DISTINCT B.USER_ID) AS "USERS"
FROM ONLINE_SALE A,USER_INFO B
WHERE GENDER IS NOT NULL AND A.USER_ID = B.USER_ID
GROUP BY TO_CHAR(SALES_DATE,'YYYY'),TO_CHAR(SALES_DATE,'MM'),GENDER
ORDER BY YEAR , MONTH , GENDER