-- 코드를 입력하세요
SELECT *
FROM
    (SELECT *
     FROM(
            SELECT A.ANIMAL_ID, A.NAME
            FROM ANIMAL_INS A, ANIMAL_OUTS B
            WHERE A.ANIMAL_ID = B.ANIMAL_ID
            ORDER BY B.DATETIME - A.DATETIME DESC
      )
     )
WHERE ROWNUM >=1 AND ROWNUM <=2