-- 코드를 입력하세요
SELECT PRODUCT_CODE,sum((PRICE*SALES_AMOUNT)) as SALES
from PRODUCT,OFFLINE_SALE
where PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
group by PRODUCT_CODE
order by SALES desc, PRODUCT_CODE