SELECT  A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, round(avg(REVIEW_SCORE),2) as SCORE
FROM REST_INFO A  INNER JOIN REST_REVIEW B  ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS like '서울%'
GROUP BY
    A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
order by SCORE desc, A.FAVORITES desc
