SELECT '/home/grep/src/' || a.BOARD_ID || '/' || b.FILE_ID || b.FILE_NAME || b.FILE_EXT AS FILE_PATH
FROM (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    FETCH FIRST 1 ROW ONLY
) a
JOIN USED_GOODS_FILE b ON a.BOARD_ID = b.BOARD_ID
ORDER BY b.FILE_ID DESC;